### ISSUE TITLE
assets creator?

### ISSUE THREAD

**Issue by rogueyoshi** [libretro/lutro-platformer#1]
who made the art for this sample platformer game?

**Comment by kivutar** [comment]
hi, I did them

**Comment by rogueyoshi** [comment]
i envy you polymaths... anyways i may want to commission you for some assets in the same style eventually if you have the time.

**Comment by kivutar** [comment]
Thanks, I think you can find better artists here http://www.pixeljoint.com/

**Comment by Alcaro** [comment]
This ... isn't an issue, is it?
